"""Add bio and accomplishments to user

Revision ID: d80b78c393f9
Revises: aea27e55028b
Create Date: 2025-05-22 15:03:51.894223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80b78c393f9'
down_revision = 'aea27e55028b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('accomplishments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('accomplishments')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
